### ISSUE TITLE
500 Failed to lookup view "index"

### ISSUE THREAD

**Issue by MaluNoPeleke** [oswaldoacauan/ghostium#119]
After enabling this theme in ghost 0.4.2 I only get a "
500
Failed to lookup view "index"
error message

**Comment by Kikobeats** [comment]
any idea about this? :_(

**Comment by seanichol** [comment]
I'm pretty sure this theme has been abandoned.

**Comment by Zacaria** [comment]
Answer for posterity
When you clone the theme you get at its root a .git folder
The problem is that when you want to add into your openshift git remote, there is a conflict.
The deeper .git folder takes the lead.
So the server receives an empty folder theme
And of course there is no index file
