### ISSUE TITLE
Noto Serif font instead of Droid Serif

### ISSUE THREAD

**Issue by Ardakilic** [oswaldoacauan/ghostium#129]
Hello,

Droid serif does not have Latin extended subset, that's why I cannot see Turkish Characters like Ş, ş etc. in blog content properly.

Instead, may I suggest using Noto Serif (which is derived from Droid Serif), which looks quite (maybe 99,9%) identical, same license, and also have latin-extended subset.

Droid Serif: http://www.google.com/fonts/specimen/Droid+Serif
Noto Serif: http://www.google.com/fonts/specimen/Noto+Serif

E.g: CTRL+F and try searching "Ş" , in Droid serif, there is no such character.

Here's a how Droid Serif looks in Turkish characters in Windows (in Linux, it's even worse):

![http://i.imgur.com/v6rsQPE.png](http://i.imgur.com/v6rsQPE.png)

Check ğ, ı and ş (and capitals).

This is after switching to Noto Serif in Firefox:

![http://i.imgur.com/w53xkmt.png](http://i.imgur.com/w53xkmt.png)

Example blog using Noto Serif instead of Droid Serif: http://arda.pw/

I'd appreciate if this is considered.

Thanks,

**Comment by Ardakilic** [comment]
Hello @oswaldoacauan , since I caught you active I wanted to ask if you'd like a pull request for this I'll gladly make one, such as https://github.com/stevelacey/ghostium/pull/1

Thank you!

**Comment by oswaldoacauan** [comment]
![JUST DO IT](https://media.giphy.com/media/10FUfTApAeoZK8/giphy.gif)
