### ISSUE TITLE
Will you add Highlightsyntax in the theme

### ISSUE THREAD

**Issue by Aaron1992** [oswaldoacauan/ghostium#131]
I am a developer and highlight.js is a very use tool for me. I combined it to my fork. And I want to kown that if you will add this feture in the theme here.

**Comment by qianyanseu** [comment]
Syntax highlighting has always been supported by ghostium, since I began to use this theme more than a year ago.

The trick is to specify what language you are using after the ``` mark, for example:

```
```python
def index(request):
	context = RequestContext(request, {})
	return render(request, 'index.html', context)  # Value Error will be raised by the 3rd parameter
```
```
