### ISSUE TITLE
Is this alive?

### ISSUE THREAD

**Issue by chaoszhuo** [oswaldoacauan/ghostium#145]
**I think that this theme is great, but the last update is about a year ago. Is this still alive for upgrade in future?**

**Comment by Ardakilic** [comment]
There's a fork, which is more active and maintained by @stevelacey . Check it out:

https://github.com/stevelacey/ghostium/

**Comment by JustinAiken** [comment]
:+1:

**Comment by stevelacey** [comment]
@oswaldoacauan just made me a contributor, hopefully there will be more life 😄
