### ISSUE TITLE
Navigation bar/menu not working at all

### ISSUE THREAD

**Issue by 0xicl33n** [oswaldoacauan/ghostium#157]
What am i doing wrong? The button just wont work. I keep just..clicking it and clicking it and nothing happens. Ive done chown work and the ghost user does own the entire folder. The online demo works just fine but for some reason on my page it wont? Why?

https://hjndkbaoisuh63h3.onion.to/

**Comment by slin1202** [comment]
Hey man, just add this code to your footer:

<script type="text/javascript">  
  if (typeof jQuery == 'undefined') {
    document.write('<script type="text/javascript" src="http://code.jquery.com/jquery-1.8.3.min.js"></'+'script>');
  }
</script>

**Comment by 0xicl33n** [comment]
Yea i actually found that on the ghost support (slack) 

But thanks anyway. Someone needs to fix that in this theme...
