### ISSUE TITLE
Font Awesome Icons Not All Appearing in Firefox (Possibly IE?)

### ISSUE THREAD

**Issue by Artiavis** [oswaldoacauan/ghostium#53]
I noticed when checking both my site and your example site that certain Font Awesome icons, such as the Twitter icon in the tray, as well as both the "Share to Facebook" and "Share to Twitter" buttons/icons which appear at the end of posts, don't appear in Firefox. (I can't test on Internet Explorer as my computer is wonky.) However, most of them do. Not sure why that would be.

**Comment by JustinAiken** [comment]
Facebook/Twitter not working on Mac/Chrome, all other icons work fine.
