### ISSUE TITLE
Menu not loading

### ISSUE THREAD

**Issue by andyleejordan** [oswaldoacauan/ghostium#84]
I just installed Ghostium following the documentation (clone, restart, good to go, eh?). Well something's not working, and I'm not sure what. Here's the [site](https://schwartzmeyer.com).
- The left-side image is stuck loading (loads fine in admin, also tried with different image  and without image)
- Clicking the menu does nothing
- Clicking posts does work, but does not use pjax

I'm not sure what's going on, all I can think of is that I am running the latest Ghost (0.4.2).

I've tried without any changes as well (so just plain Ghostium theme) and am having the issues in Chromium and Safari on OS X. I've also restarted my server and ensured the folder is owned by the proper user (ghost, in my case).

Any ideas? I really like Ghostium, if I can get it working.

**Comment by Mindstormer619** [comment]
Wait, I'm still having these errors on a fresh install of Ghost 0.7 and Ghostium. What is the fix? @andschwa

**Comment by andschwa** [comment]
@Mindstormer619 Are you trying to use a reserved slug somewhere else? I was proxying `/public` elsewhere, which broke things. Check the reserved slugs.

**Comment by Mindstormer619** [comment]
@andschwa No dude, perfectly fresh install. Steps I followed were this:

- Download and unpack ghost
- `npm install --production`
- `npm start --production`
- Ghost works with Casper theme
- Clone Ghostium into `/content/themes/ghostium`
- Start ghost server
- Change settings from admin panel for theme

**Comment by andschwa** [comment]
@Mindstormer619 I don't know for sure if this caused your issue, but Ghost just changed when they include jQuery: [jQuery not included in `{{ghost_foot}}`
](http://dev.ghost.org/ghost-0-7-0/). I would look into that, as it's possible that Ghostium needs to be updated to include jQuery in places where before it didn't.

**Comment by Mindstormer619** [comment]
@andschwa Yeah, that's probably it. Thanks. I guess Ghostium needs to update to include jquery now.
